window.TalkTagAudioLessons = (window.TalkTagAudioLessons || []).concat([
  {
    "id": "aea-a1-001",
    "level": "A1",
    "title": "A Quiet Morning",
    "expressions": [
      "Every morning, I get up at seven. I open the window and look outside. The street is quiet, and the air is cool.",
      "I make a cup of coffee and sit by the window. Sometimes, I listen to music. Sometimes, I just enjoy the quiet morning.",
      "At eight, I get ready for work. I put on my shoes, take my bag, and leave home.",
      "It is a simple morning, but I like it."
    ],
    "type": "plain",
    "unit": "001",
    "genre": "Daily Life",
    "art": "聴",
    "description": "조용한 아침",
    "summary": "이야기를 듣고, 핵심 내용을 정리한 뒤 자신의 말로 다시 이야기해 보세요.",
    "meanings": [
      "매일 아침 일곱 시에 일어납니다. 창문을 열고 밖을 내다봅니다. 거리는 조용하고 공기는 선선합니다.",
      "커피 한 잔을 만들어 창가에 앉습니다. 가끔 음악을 듣기도 하고, 아무것도 하지 않은 채 조용한 아침을 즐기기도 합니다.",
      "여덟 시가 되면 출근 준비를 합니다. 신발을 신고 가방을 챙겨 집을 나섭니다.",
      "아주 평범한 아침이지만, 저는 이런 시간이 좋습니다."
    ],
    "audio": "https://audio.talktag.co.kr/English/Audio%20Essays%20%26%20Articles/A1/A%20quiet%20morning%20A1%20Essay.mp3",
    "durationLabel": "00:28",
    "durationLong": "00:28",
    "titleKo": "조용한 아침",
    "referenceSummary": "The speaker enjoys a simple and quiet morning routine before going to work. A cup of coffee and a little quiet time make the morning pleasant."
  },
  {
    "id": "aea-a2-001",
    "level": "A2",
    "title": "The Little Bakery",
    "expressions": [
      "There is a small bakery near my house. I often stop there on my way home from work.",
      "The bakery is not big, but it always smells wonderful. They make fresh bread every afternoon. My favorite is the cheese bread, but sometimes I buy a chocolate cake for my family.",
      "The owner is an older woman named Mrs. Lee. She always smiles and asks me about my day.",
      "Yesterday, I was tired after work. I went into the bakery, bought some bread, and talked with Mrs. Lee for a few minutes.",
      "When I left, I felt much better.",
      "Sometimes, a small place can make a long day feel a little easier."
    ],
    "type": "plain",
    "unit": "001",
    "genre": "Mini Story",
    "art": "聴",
    "description": "작은 빵집",
    "summary": "이야기를 듣고, 핵심 내용을 정리한 뒤 자신의 말로 다시 이야기해 보세요.",
    "meanings": [
      "우리 집 근처에는 작은 빵집이 하나 있습니다. 퇴근길에 저는 종종 그곳에 들릅니다.",
      "크지 않은 빵집이지만 안에 들어서면 언제나 갓 구운 빵 냄새가 반겨 줍니다.",
      "매일 오후 신선한 빵이 나오는데, 제가 가장 좋아하는 것은 치즈빵입니다. 가끔은 가족과 함께 먹으려고 초콜릿 케이크를 사기도 합니다.",
      "가게 주인은 나이 지긋한 이 씨입니다. 늘 웃으며 오늘 하루는 어땠는지 물어봅니다.",
      "어제는 일을 마치고 무척 피곤했습니다. 빵집에 들러 빵을 사고 이 씨와 몇 분 동안 이야기를 나누었습니다.",
      "빵집을 나설 때는 들어갈 때보다 기분이 한결 나아져 있었습니다.",
      "때로는 작은 공간 하나가 길고 고단했던 하루를 조금은 가볍게 만들어 주기도 합니다."
    ],
    "audio": "https://audio.talktag.co.kr/English/Audio%20Essays%20%26%20Articles/A2/The%20Little%20Bakery%20A2%20Essay.mp3",
    "durationLabel": "00:43",
    "durationLong": "00:43",
    "titleKo": "작은 빵집",
    "referenceSummary": "The speaker often visits a small bakery near home. One tiring day, buying bread and talking with the friendly owner helps the speaker feel better."
  },
  {
    "id": "aea-b1-001",
    "level": "B1",
    "title": "Taking the Longer Way Home",
    "expressions": [
      "I usually take the fastest route home after work. I want to get home, eat dinner, and rest as soon as possible.",
      "But a few weeks ago, I started doing something different.",
      "Instead of taking the main road, I began walking through a small park near my neighborhood. It takes about fifteen minutes longer, but I don't mind.",
      "There are trees along the path, and I often see people walking their dogs or exercising. Sometimes I sit on a bench for a few minutes and watch people go by.",
      "At first, I thought I was wasting time. Then I noticed that I was arriving home in a better mood.",
      "The extra fifteen minutes give me time to leave the day behind.",
      "Now I understand that the fastest way home is not always the best way home."
    ],
    "type": "plain",
    "unit": "001",
    "genre": "Personal Essay",
    "art": "聴",
    "description": "조금 더 먼 길로 집에 가기",
    "summary": "이야기를 듣고, 핵심 내용을 정리한 뒤 자신의 말로 다시 이야기해 보세요.",
    "meanings": [
      "저는 퇴근할 때 보통 가장 빠른 길로 집에 갑니다. 가능한 한 빨리 집에 도착해 저녁을 먹고 쉬고 싶기 때문입니다.",
      "그런데 몇 주 전부터 조금 다른 길을 택하기 시작했습니다.",
      "큰길 대신 동네에 있는 작은 공원을 가로질러 걷습니다. 집에 도착하는 데 15분쯤 더 걸리지만 이제는 그 시간이 아깝지 않습니다.",
      "산책로 양옆에는 나무가 늘어서 있고, 강아지를 산책시키거나 운동하는 사람들도 자주 보입니다. 가끔은 벤치에 잠시 앉아 지나가는 사람들을 바라보기도 합니다.",
      "처음에는 괜히 시간을 낭비하는 것 같았습니다. 하지만 얼마 지나지 않아 한 가지를 깨달았습니다.",
      "이 길로 집에 돌아가는 날에는 집에 도착했을 때 마음이 훨씬 편안해져 있었습니다.",
      "그 15분이 하루의 일들을 뒤로하고 마음을 정리할 시간을 만들어 주었던 것입니다.",
      "이제는 알 것 같습니다.",
      "집으로 가는 가장 빠른 길이 언제나 가장 좋은 길은 아니라는 것을요."
    ],
    "audio": "https://audio.talktag.co.kr/English/Audio%20Essays%20%26%20Articles/B1/Taking%20the%20Longer%20Way%20Home%20B1%20Essay.mp3",
    "durationLabel": "00:52",
    "durationLong": "00:52",
    "titleKo": "조금 더 먼 길로 집에 가기",
    "referenceSummary": "The speaker starts taking a longer route home through a park. Although it takes more time, the walk helps the speaker relax and arrive home in a better mood."
  },
  {
    "id": "aea-b2-001",
    "level": "B2",
    "title": "Why We Need Places Where Nothing Is Expected of Us",
    "expressions": [
      "Most of the places we visit have a purpose.",
      "We go to the office to work, to the gym to exercise, and to a store to buy something. Even at home, there are often things waiting for us—laundry, dishes, messages, or unfinished work.",
      "That's why I think we need places where nothing is expected of us.",
      "For some people, that place is a quiet café. For others, it might be a park, a library, or even a bench beside a river.",
      "The important thing is not the location itself. What matters is that, for a short time, we don't have to accomplish anything.",
      "Modern life encourages us to use every minute efficiently. We listen to podcasts while walking, answer messages while eating, and check our phones whenever we have a free moment.",
      "None of these habits is necessarily bad. The problem begins when we forget how to simply be somewhere.",
      "A quiet twenty minutes may look unproductive from the outside. Yet those twenty minutes can give our minds space to slow down, notice things, and recover.",
      "Perhaps rest is not the opposite of doing something useful.",
      "Perhaps sometimes, rest is the useful thing."
    ],
    "type": "plain",
    "unit": "001",
    "genre": "Lifestyle Article",
    "art": "聴",
    "description": "아무것도 하지 않아도 되는 곳이 필요한 이유",
    "summary": "이야기를 듣고, 핵심 내용을 정리한 뒤 자신의 말로 다시 이야기해 보세요.",
    "meanings": [
      "우리가 찾아가는 대부분의 장소에는 저마다 분명한 목적이 있습니다.",
      "회사에는 일을 하러 가고, 헬스장에는 운동을 하러 가며, 가게에는 무언가를 사러 갑니다.",
      "집이라고 해서 크게 다르지는 않습니다. 돌아가면 빨래와 설거지가 기다리고 있고, 답해야 할 메시지나 끝내지 못한 일이 남아 있기도 합니다.",
      "그래서 우리에게는 가끔 아무것도 하지 않아도 되는 곳이 필요합니다.",
      "누군가에게는 조용한 카페일 수 있고, 다른 사람에게는 공원이나 도서관, 혹은 강가의 벤치 하나일 수도 있습니다.",
      "중요한 것은 장소가 어디냐가 아닙니다. 잠시 동안만이라도 무언가를 해내야 한다는 부담에서 벗어날 수 있다는 것이 중요합니다.",
      "현대의 삶은 매 순간을 효율적으로 사용하라고 우리를 재촉합니다.",
      "걸으면서 팟캐스트를 듣고, 밥을 먹으면서 메시지에 답하고, 잠깐 시간이 비면 습관처럼 휴대전화를 확인합니다.",
      "이런 행동 자체가 나쁜 것은 아닙니다.",
      "문제는 우리가 아무것도 하지 않은 채 그저 한곳에 가만히 머무는 법을 잊어버릴 때 생깁니다.",
      "조용히 보내는 20분은 겉으로 보기에는 별로 생산적이지 않은 시간처럼 보일 수 있습니다.",
      "하지만 바로 그런 시간이 우리의 마음을 천천히 가라앉히고, 주변을 다시 바라보게 하며, 지친 마음을 회복할 여유를 줍니다.",
      "어쩌면 휴식은 유용한 일을 하지 않는 시간이 아닐지도 모릅니다.",
      "때로는 쉬는 일이야말로 가장 필요한 일일 수 있습니다."
    ],
    "audio": "https://audio.talktag.co.kr/English/Audio%20Essays%20%26%20Articles/B2/Why%20We%20Need%20Places%20Where%20Nothing%20Is%20Expected%20of%20Us%20B2%20Essay.mp3",
    "durationLabel": "01:20",
    "durationLong": "01:20",
    "titleKo": "아무것도 하지 않아도 되는 곳이 필요한 이유",
    "referenceSummary": "Modern life constantly gives us things to do. The article argues that we need places where nothing is expected of us because quiet, apparently unproductive time can help our minds slow down and recover."
  },
  {
    "id": "aea-c1-001",
    "level": "C1",
    "title": "The Disappearing Art of Being Temporarily Unavailable",
    "expressions": [
      "There was a time when being unreachable was an ordinary part of daily life.",
      "Someone could leave the house in the morning, spend several hours away, and return without having received a single message. Unless there was an emergency, nobody found this particularly strange.",
      "Smartphones have quietly changed that expectation.",
      "Today, carrying a phone often means carrying an invisible obligation to remain available. A message arrives, we see it, and a small decision immediately follows: Should I answer now? Can it wait? Will the other person think I'm ignoring them?",
      "Individually, these decisions seem insignificant. Collectively, however, they create a subtle form of mental pressure.",
      "The issue is not simply that technology distracts us. Technology has also changed what other people can reasonably expect from us. Once instant communication becomes possible, delayed communication can begin to look intentional.",
      "This makes genuine disconnection surprisingly difficult.",
      "Turning off notifications helps, but it doesn't completely solve the problem because the expectation remains in our minds. We know that messages may be waiting.",
      "Perhaps what we need, then, is not another productivity technique but a renewed social agreement: people should be allowed to disappear for a while.",
      "A walk without a phone, an unanswered message during dinner, or an afternoon spent offline should not require an explanation.",
      "Being temporarily unavailable is not necessarily a rejection of other people.",
      "Sometimes it is simply a way of becoming fully available to the life directly in front of us."
    ],
    "type": "plain",
    "unit": "001",
    "genre": "Social Commentary",
    "art": "聴",
    "description": "잠시 연락이 닿지 않아도 되는 자유",
    "summary": "이야기를 듣고, 핵심 내용을 정리한 뒤 자신의 말로 다시 이야기해 보세요.",
    "meanings": [
      "연락이 되지 않는 것이 아주 자연스러운 일이던 시절이 있었습니다.",
      "아침에 집을 나선 사람이 몇 시간 동안 밖에 있다가 메시지 하나 받지 않은 채 돌아오는 일도 흔했습니다.",
      "긴급한 일이 아니라면 누구도 그것을 이상하게 여기지 않았습니다.",
      "하지만 스마트폰은 이런 우리의 기대를 조용히 바꾸어 놓았습니다.",
      "이제 휴대전화를 들고 다닌다는 것은 언제든 연락을 받을 준비가 되어 있어야 한다는 보이지 않는 의무까지 함께 지니고 다니는 것처럼 느껴집니다.",
      "메시지가 도착하면 우리는 자연스럽게 작은 고민을 시작합니다.",
      "지금 답해야 할까? 나중에 답해도 괜찮을까? 상대방이 내가 일부러 무시한다고 생각하지는 않을까?",
      "하나하나 놓고 보면 별것 아닌 고민처럼 보입니다. 하지만 이런 순간들이 하루에도 여러 번 반복되면 조금씩 정신적인 부담이 쌓입니다.",
      "문제는 단순히 기술이 우리의 집중력을 흐트러뜨린다는 데 있지 않습니다.",
      "기술은 다른 사람들이 우리에게 무엇을 당연히 기대할 수 있는지까지 바꾸어 놓았습니다.",
      "언제든 즉시 연락할 수 있게 되면서, 답장이 늦는 것조차 일부러 그러는 것처럼 보이기 시작했습니다.",
      "그래서 완전히 연결을 끊고 쉬는 일이 생각보다 훨씬 어려워졌습니다.",
      "알림을 꺼두면 어느 정도 도움이 됩니다. 하지만 그것만으로는 충분하지 않습니다.",
      "휴대전화를 보고 있지 않아도 어딘가에 확인하지 않은 메시지가 기다리고 있을지 모른다는 사실을 우리는 알고 있기 때문입니다.",
      "어쩌면 우리에게 필요한 것은 또 하나의 생산성 관리법이 아닐지도 모릅니다.",
      "오히려 새로운 사회적 합의가 필요할 수 있습니다.",
      "사람에게는 누구나 잠시 연락이 닿지 않아도 되는 시간이 있어야 한다는 합의입니다.",
      "휴대전화 없이 산책을 하는 것, 저녁을 먹는 동안 메시지에 답하지 않는 것, 오후 몇 시간을 오프라인으로 보내는 것에 굳이 이유를 설명할 필요가 없어야 합니다.",
      "잠시 연락이 되지 않는다고 해서 다른 사람을 밀어내는 것은 아닙니다.",
      "때로는 눈앞에 있는 삶에 온전히 집중하기 위해 다른 연결에서 잠시 벗어나는 것일 뿐입니다."
    ],
    "audio": "https://audio.talktag.co.kr/English/Audio%20Essays%20%26%20Articles/C1/The%20Disappearing%20Art%20of%20Being%20Temporarily%20Unavailable%20C1%20Essay.mp3",
    "durationLabel": "01:56",
    "durationLong": "01:56",
    "titleKo": "잠시 연락이 닿지 않아도 되는 자유",
    "referenceSummary": "Smartphones have created an expectation that people should always be reachable. The essay argues that constant availability creates subtle mental pressure and that society should accept temporary disconnection as a normal and healthy part of life."
  },
  {
    "id": "aea-c2-001",
    "level": "C2",
    "title": "The Things We Stop Noticing",
    "expressions": [
      "One of the peculiar consequences of familiarity is that it gradually makes the visible world disappear.",
      "When we enter an unfamiliar neighborhood, almost everything demands our attention: the shape of the buildings, the rhythm of the traffic, fragments of conversation, the smell drifting from a restaurant whose name we cannot pronounce. We are alert because we do not yet know what matters.",
      "Return to the same place every day, however, and much of this richness begins to fade.",
      "The bakery on the corner becomes simply \"the bakery.\" The elderly man who waters the plants outside his shop becomes part of the scenery. Even the changing light on buildings we have passed a thousand times can cease to register.",
      "This fading of attention is not a defect. Without it, ordinary life would overwhelm us. The brain becomes efficient precisely by deciding what it no longer needs to examine closely.",
      "Yet efficiency carries a subtle cost.",
      "When familiarity tells us that we already know a place, a person, or even an idea, curiosity tends to withdraw. We stop looking because we assume there is nothing left to see.",
      "The same phenomenon occurs in relationships. A stranger's story can fascinate us because every detail is new. With someone we have known for twenty years, we may begin to believe that we already understand the entire person.",
      "Of course, we don't.",
      "People continue to change beneath the identities we assign to them, just as familiar streets continue to change beneath our routines.",
      "Perhaps attention, then, is not merely something the world captures from us. It is something we can deliberately return to the world.",
      "We can take a different street home. We can ask an old friend a question we have never asked. We can sit in a familiar room and notice what has been there all along.",
      "The remarkable does not always require discovery.",
      "Sometimes it requires rediscovery."
    ],
    "type": "plain",
    "unit": "001",
    "genre": "Reflective Essay",
    "art": "聴",
    "description": "우리가 더 이상 눈여겨보지 않는 것들",
    "summary": "이야기를 듣고, 핵심 내용을 정리한 뒤 자신의 말로 다시 이야기해 보세요.",
    "meanings": [
      "익숙함이 가져오는 묘한 변화 가운데 하나는 눈앞의 세상을 서서히 보이지 않게 만든다는 것입니다.",
      "낯선 동네에 처음 들어서면 거의 모든 것이 우리의 시선을 붙잡습니다.",
      "건물의 모양, 차들이 오가는 흐름, 스쳐 지나가는 대화의 한 조각, 이름조차 제대로 읽기 어려운 식당에서 풍겨오는 냄새까지 모두 눈과 귀에 들어옵니다.",
      "아직 무엇이 중요하고 무엇이 중요하지 않은지 모르기 때문에 우리는 자연스럽게 주변을 세심하게 살핍니다.",
      "하지만 같은 장소를 매일 오가다 보면 처음에는 그토록 생생했던 풍경이 조금씩 희미해지기 시작합니다.",
      "모퉁이의 빵집은 어느새 그저 '그 빵집'이 되고, 가게 앞 화분에 물을 주는 노인은 풍경의 일부처럼 느껴집니다.",
      "수없이 지나친 건물 위로 빛이 시시각각 달라지는 모습도 어느 순간부터는 더 이상 의식하지 않게 됩니다.",
      "그렇다고 해서 우리의 주의력이 무뎌지는 것이 결함이라는 뜻은 아닙니다.",
      "모든 것을 매번 새롭게 받아들여야 한다면 평범한 하루조차 감당하기 어려울 만큼 복잡해질 것입니다.",
      "우리의 뇌는 더 이상 자세히 살펴볼 필요가 없다고 판단한 것들을 배경으로 밀어냄으로써 효율적으로 작동합니다.",
      "하지만 그 효율에는 눈에 잘 띄지 않는 대가가 따릅니다.",
      "익숙함이 어떤 장소나 사람, 혹은 생각에 대해 이미 충분히 알고 있다고 느끼게 만들면 호기심은 슬그머니 물러납니다.",
      "더 이상 새롭게 볼 것이 없다고 생각하기 때문에 자세히 바라보지 않게 되는 것입니다.",
      "인간관계에서도 비슷한 일이 일어납니다.",
      "처음 만난 사람의 이야기는 모든 것이 새롭기 때문에 흥미롭게 들립니다.",
      "하지만 20년을 알고 지낸 사람에게는 그 사람을 이미 다 알고 있다는 착각에 빠지기 쉽습니다.",
      "물론 그렇지 않습니다.",
      "익숙한 거리가 우리가 늘 같은 길을 걷는 동안에도 계속 변하고 있듯, 사람 역시 우리가 그에게 붙여놓은 이미지와 상관없이 계속해서 변해 갑니다.",
      "어쩌면 주의를 기울인다는 것은 세상이 우리의 관심을 끌어가는 일만을 뜻하지 않을지도 모릅니다.",
      "우리가 마음먹고 다시 세상에 건넬 수 있는 것이기도 합니다.",
      "평소와 다른 길로 집에 가볼 수 있습니다.",
      "오래된 친구에게 한 번도 해보지 않았던 질문을 던져볼 수도 있습니다.",
      "익숙한 방에 가만히 앉아 늘 그 자리에 있었지만 미처 보지 못했던 것을 바라볼 수도 있습니다.",
      "놀라움을 느끼기 위해 언제나 새로운 것을 발견해야 하는 것은 아닙니다.",
      "때로 우리에게 필요한 것은 새로운 발견이 아니라,",
      "익숙한 것을 다시 발견하는 일입니다."
    ],
    "audio": "https://audio.talktag.co.kr/English/Audio%20Essays%20%26%20Articles/C2/The%20Things%20We%20Stop%20Noticing%20C2%20Essay.mp3",
    "durationLabel": "02:23",
    "durationLong": "02:23",
    "titleKo": "우리가 더 이상 눈여겨보지 않는 것들",
    "referenceSummary": "Familiarity helps the brain operate efficiently, but it can also cause us to stop noticing familiar places, people, and experiences. The essay suggests that we can deliberately restore our attention and rediscover what has been around us all along."
  }
]);
