window.TalkTagAudioLessons = [
  {
    "id": "guided-a1-01",
    "type": "guided",
    "level": "A1",
    "part": 1,
    "chapter": 1,
    "unit": 1,
    "title": "Put It Away",
    "art": "01",
    "description": "Basic food storage and kitchen actions",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "9:22",
    "durationLong": "9:22",
    "audio": "https://audio.talktag.co.kr/English/guided/20261008-12episodes/a1-01/training-10.mp3",
    "expressions": [
      "Put the milk in the fridge.",
      "Keep the ice cream in the freezer.",
      "Take the chicken out of the freezer.",
      "Wash the apples before you eat them.",
      "Put the leftovers in a container.",
      "Close the fridge door.",
      "Throw the empty box away.",
      "Let's clean up the kitchen."
    ],
    "meanings": [],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 561.8941043083901
    }
  },
  {
    "id": "guided-a1-02",
    "type": "guided",
    "level": "A1",
    "part": 2,
    "chapter": 1,
    "unit": 2,
    "title": "Make a Simple Snack",
    "art": "02",
    "description": "Basic preparation actions",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "8:29",
    "durationLong": "8:29",
    "audio": "https://audio.talktag.co.kr/English/guided/20261008-12episodes/a1-02/training-10.mp3",
    "expressions": [
      "Peel the apple first.",
      "Cut it into small pieces.",
      "Slice the cucumber really thin.",
      "Put everything in a bowl.",
      "Add a little salt.",
      "Pour in some dressing.",
      "Mix it all together.",
      "Now it's ready to eat."
    ],
    "meanings": [],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 508.8657596371882
    }
  },
  {
    "id": "guided-a2-01",
    "type": "guided",
    "level": "A2",
    "part": 1,
    "chapter": 1,
    "unit": 1,
    "title": "Making Breakfast",
    "art": "01",
    "description": "A simple cooking sequence",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "12:05",
    "durationLong": "12:05",
    "audio": "https://audio.talktag.co.kr/English/guided/20261008-12episodes/a2-01/training-10.mp3",
    "expressions": [
      "I'm making breakfast before work.",
      "Can you boil some water for me?",
      "I'll crack two eggs into a bowl.",
      "Whisk them until they're well mixed.",
      "Heat the pan over medium heat.",
      "Pour the eggs into the pan.",
      "Toast two slices of bread.",
      "Spread some butter on the toast.",
      "I'll make coffee while the eggs cook.",
      "Breakfast will be ready in five minutes."
    ],
    "meanings": [],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 724.6374149659864
    }
  },
  {
    "id": "guided-a2-02",
    "type": "guided",
    "level": "A2",
    "part": 2,
    "chapter": 1,
    "unit": 2,
    "title": "Getting Dinner Ready",
    "art": "02",
    "description": "Preparing vegetables and setting the table",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "13:49",
    "durationLong": "13:49",
    "audio": "https://audio.talktag.co.kr/English/guided/20261008-12episodes/a2-02/training-10.mp3",
    "expressions": [
      "I'm getting dinner ready now.",
      "Please rinse the vegetables under cold water.",
      "Chop the carrots into small pieces.",
      "Slice the mushrooms a little thinner.",
      "Heat some oil in a large pan.",
      "Add the vegetables and stir them around.",
      "Turn the heat down if they start cooking too fast.",
      "Can you set the table while I finish cooking?",
      "I'll serve the food in a minute.",
      "Let's save the leftovers for tomorrow."
    ],
    "meanings": [],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 827.9517006802721
    }
  },
  {
    "id": "guided-b1-01",
    "type": "guided",
    "level": "B1",
    "part": 1,
    "chapter": 1,
    "unit": 1,
    "title": "Dinner from What We Have",
    "art": "01",
    "description": "Improvising a meal with useful phrasal language",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "17:43",
    "durationLong": "17:43",
    "audio": "https://audio.talktag.co.kr/English/guided/20261008-12episodes/b1-01/training-10.mp3",
    "expressions": [
      "We don't have much food left, so let's use what we have.",
      "I found some vegetables that need to be used up today.",
      "Let's chop them up and cook them with some rice.",
      "We can add an egg if we want a little more protein.",
      "I'll heat the pan while you cut the vegetables.",
      "Don't turn the heat up too high, or the garlic will burn.",
      "If the rice is too dry, add a little water and stir it in.",
      "Let's taste it before we add any more salt.",
      "This actually turned out better than I expected.",
      "Pack the rest up so we can have it for lunch tomorrow."
    ],
    "meanings": [],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 1062.9231292517006
    }
  },
  {
    "id": "guided-b1-02",
    "type": "guided",
    "level": "B1",
    "part": 2,
    "chapter": 1,
    "unit": 2,
    "title": "Around the Dinner Table",
    "art": "02",
    "description": "Serving, eating, and reacting naturally",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "14:20",
    "durationLong": "14:20",
    "audio": "https://audio.talktag.co.kr/English/guided/20261008-12episodes/b1-02/training-10.mp3",
    "expressions": [
      "Go ahead and help yourself.",
      "Can you pass me the rice, please?",
      "Try the soup before it gets cold.",
      "This is good, but it could use a little more salt.",
      "I'll just have a small piece.",
      "Do you want some more, or are you full?",
      "I ate too fast because I was really hungry.",
      "Save some room for dessert.",
      "We can clear the table after everyone finishes.",
      "I'll put the leftovers away before we go to bed."
    ],
    "meanings": [],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 859.0374149659864
    }
  },
  {
    "id": "guided-b2-01",
    "type": "guided",
    "level": "B2",
    "part": 1,
    "chapter": 1,
    "unit": 1,
    "title": "Cooking When You're in a Hurry",
    "art": "01",
    "description": "Adjusting plans and explaining choices",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "21:00",
    "durationLong": "21:00",
    "audio": "https://audio.talktag.co.kr/English/guided/20261008-12episodes/b2-01/training-10.mp3",
    "expressions": [
      "I got home late, so I need to make something quick.",
      "Instead of cooking from scratch, I'm using a few things I already prepared.",
      "I'll heat the soup while the rice is warming up.",
      "The vegetables are already chopped, which saves a lot of time.",
      "If the sauce gets too thick, just add a splash of water.",
      "I'm keeping the heat fairly low so nothing sticks to the pan.",
      "We don't need anything fancy tonight; we just need something decent to eat.",
      "I'd rather make a simple meal than order food again.",
      "Once everything is hot, we can sit down and relax.",
      "On busy days, having a few basics ready makes a huge difference."
    ],
    "meanings": [],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 1259.4945578231293
    }
  },
  {
    "id": "guided-b2-02",
    "type": "guided",
    "level": "B2",
    "part": 2,
    "chapter": 1,
    "unit": 2,
    "title": "Having Friends Over",
    "art": "02",
    "description": "Hosting and adapting food for other people",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "20:45",
    "durationLong": "20:45",
    "audio": "https://audio.talktag.co.kr/English/guided/20261008-12episodes/b2-02/training-10.mp3",
    "expressions": [
      "A few friends are coming over, so I'm keeping the menu simple.",
      "I'm making one main dish and a couple of easy sides.",
      "One of my friends doesn't eat meat, so I'm making a separate option.",
      "I've already chopped most of the vegetables to save time later.",
      "Can you taste the sauce and tell me if it needs anything?",
      "I don't want the food to be too spicy for everyone.",
      "We can keep the dishes warm until the last person arrives.",
      "Once everyone's here, I'll put everything in the middle of the table.",
      "I like meals where people can serve themselves and try a little of everything.",
      "The food matters, but the point is really to spend time together."
    ],
    "meanings": [],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 1244.8657596371881
    }
  },
  {
    "id": "guided-c1-01",
    "type": "guided",
    "level": "C1",
    "part": 1,
    "chapter": 1,
    "unit": 1,
    "title": "Why I Cook at Home",
    "art": "01",
    "description": "Natural reflection on habits, control, and waste",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "28:36",
    "durationLong": "28:36",
    "audio": "https://audio.talktag.co.kr/English/guided/20261008-12episodes/c1-01/training-10.mp3",
    "expressions": [
      "I don't cook at home because I think every meal has to be healthy or impressive.",
      "I mostly do it because I like knowing what goes into my food.",
      "When I make something myself, I can adjust the salt, oil, and spice as I go.",
      "It also makes me more aware of how much food I waste.",
      "Some nights I cook a proper meal, and other nights I just throw together whatever is left in the fridge.",
      "That flexibility is probably what keeps cooking from feeling like a chore.",
      "I've also gotten better at using ingredients before they go bad.",
      "Over time, I've learned that being a decent home cook is less about fancy recipes and more about knowing a few reliable techniques.",
      "For me, cooking is practical first, but there's something satisfying about making an ordinary meal well.",
      "That's usually enough to make me want to do it again the next day."
    ],
    "meanings": [],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 1715.722902494331
    }
  },
  {
    "id": "guided-c1-02",
    "type": "guided",
    "level": "C1",
    "part": 2,
    "chapter": 1,
    "unit": 2,
    "title": "What Makes a Meal Feel Special",
    "art": "02",
    "description": "Spoken reflection on food, memory, and company",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "28:58",
    "durationLong": "28:58",
    "audio": "https://audio.talktag.co.kr/English/guided/20261008-12episodes/c1-02/training-10.mp3",
    "expressions": [
      "A special meal doesn't always have to be expensive or carefully planned.",
      "Sometimes it's just familiar food served at the right moment.",
      "I've had simple meals that I remember more clearly than dinners at expensive restaurants.",
      "The difference was usually the people I was with and the mood around the table.",
      "Good food helps, of course, but it doesn't have to be complicated.",
      "A dish can be meaningful because someone took the time to make it for you.",
      "It can also remind you of a place, a person, or a particular period of your life.",
      "That's why certain smells or flavors can bring back memories almost instantly.",
      "For me, the best meals are the ones that make people slow down and stay at the table a little longer.",
      "The food gives everyone a reason to gather, but the conversation is what makes the meal memorable."
    ],
    "meanings": [],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 1737.6655328798186
    }
  },
  {
    "id": "guided-c2-01",
    "type": "guided",
    "level": "C2",
    "part": 1,
    "chapter": 1,
    "unit": 1,
    "title": "Convenience and Cooking Skills",
    "art": "01",
    "description": "Nuanced spoken reflection on convenience and skill",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "32:45",
    "durationLong": "32:45",
    "audio": "https://audio.talktag.co.kr/English/guided/20261008-12episodes/c2-01/training-10.mp3",
    "expressions": [
      "Convenience in the kitchen is usually treated as a simple good, and most of the time it is.",
      "Pre-cut vegetables, delivery apps, and prepared meals can save time when life is busy.",
      "The trade-off is that convenience can gradually remove the need to practice basic skills.",
      "If you rarely chop, season, or cook from scratch, those actions can start to feel more difficult than they really are.",
      "That doesn't mean everyone needs to reject convenience or turn cooking into a hobby.",
      "It just means there is value in keeping a few basic skills alive.",
      "Knowing how to make a simple meal gives you options when plans change, money is tight, or you simply don't want to order out.",
      "The skill is modest, but the independence it creates is real.",
      "I think the best balance is to use convenience deliberately rather than automatically.",
      "Tools should make life easier without quietly making us less capable."
    ],
    "meanings": [],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 1964.4086167800453
    }
  },
  {
    "id": "guided-c2-02",
    "type": "guided",
    "level": "C2",
    "part": 2,
    "chapter": 1,
    "unit": 2,
    "title": "Why People Gather Around Food",
    "art": "02",
    "description": "Nuanced spoken reflection on social life and shared meals",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "33:50",
    "durationLong": "33:50",
    "audio": "https://audio.talktag.co.kr/English/guided/20261008-12episodes/c2-02/training-10.mp3",
    "expressions": [
      "Food does more than solve hunger; it gives people a reason to gather without needing a formal agenda.",
      "A shared meal creates a natural structure for conversation because everyone is doing something together.",
      "That matters especially when people don't know one another well.",
      "Eating gives the group a common focus, which can make silence feel less awkward and conversation feel less forced.",
      "The meal itself may be simple, but the social effect can be surprisingly strong.",
      "People pass dishes, react to flavors, tell stories, and gradually become more comfortable with one another.",
      "In that sense, food often works as a kind of social bridge.",
      "It doesn't guarantee connection, and a good meal can't fix every relationship.",
      "But it can create the conditions in which people are more willing to stay, listen, and talk.",
      "Sometimes the most important thing on the table isn't the food at all; it's the time people have decided to share."
    ],
    "meanings": [],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 2029.3231292517007
    }
  }
];
