(function () {
  "use strict";
  window.TalkTagAudioLessons = [
    {
      id: "a1-head",
      type: "guided",
      level: "A1",
      part: 1,
      chapter: 1,
      unit: 1,
      title: "Head Movements",
      art: "動",
      description: "고개를 끄덕이고, 돌리고, 기울이는 기본 동작 표현을 반복 훈련합니다.",
      summary: "제공자가 반복과 침묵을 편집한 완성 음원을 그대로 듣고 따라 합니다.",
      durationLabel: "13:05",
      durationLong: "13 minutes 05 seconds",
      audio: "https://audio.talktag.co.kr/English/guided/A1/head%20A1.mp3",
      expressions: [
        "I nodded my head and said yes.",
        "He lowered his head and walked away.",
        "He turned his head toward the door.",
        "He stuck his head out of the window.",
        "The dog cocked its head.",
        "She tilted her head backward.",
        "She shook her head and said no.",
        "The boy tilted his head to the left.",
        "He bobbed his head to the music.",
        "She raised her head and looked at me."
      ],
      meanings: [
        "나는 고개를 끄덕이며 그렇다고 말했습니다.",
        "그는 고개를 숙인 채 걸어갔습니다.",
        "그는 문 쪽으로 고개를 돌렸습니다.",
        "그는 창밖으로 머리를 내밀었습니다.",
        "개가 궁금한 듯 고개를 갸웃했습니다.",
        "그녀는 고개를 뒤로 젖혔습니다.",
        "그녀는 고개를 저으며 아니라고 말했습니다.",
        "소년은 고개를 왼쪽으로 기울였습니다.",
        "그는 음악에 맞춰 머리를 까딱거렸습니다.",
        "그녀는 고개를 들어 나를 바라봤습니다."
      ]
    },
    {
      id: "a2-hair-01-03",
      type: "guided",
      level: "A2",
      part: 1,
      chapter: 1,
      unit: "3 · 01–03",
      title: "Hair Care & Haircuts",
      art: "髮",
      description: "머리를 헹구고 수건으로 감싸며, 머리를 자르는 일상 표현을 반복 훈련합니다.",
      summary: "기본적인 머리 관리와 미용실 표현을 누적 반복으로 익힙니다.",
      durationLabel: "10:46",
      durationLong: "10 minutes 46 seconds",
      audio: "https://audio.talktag.co.kr/English/guided/A2/hair1-3%20A2.mp3",
      expressions: [
        "I rinsed my hair twice.",
        "Make sure you rinse your hair well.",
        "Rinse your hair with cold water.",
        "Rinse your hair well after shampooing.",
        "She wrapped her hair in a towel.",
        "I wrapped my hair in a towel.",
        "She wrapped her hair after showering.",
        "Don't leave your hair wrapped in a towel too long.",
        "I had my hair cut yesterday.",
        "I need to have my hair cut.",
        "She had her hair cut short.",
        "Where do you usually have your hair cut?"
      ],
      meanings: [
        "나는 머리를 두 번 헹궜습니다.",
        "머리를 충분히 잘 헹구세요.",
        "찬물로 머리를 헹구세요.",
        "샴푸한 뒤 머리를 충분히 헹구세요.",
        "그녀는 머리를 수건으로 감쌌습니다.",
        "나는 머리를 수건으로 감쌌습니다.",
        "그녀는 샤워를 마친 뒤 머리를 감쌌습니다.",
        "머리를 수건으로 너무 오래 감싸 두지 마세요.",
        "나는 어제 머리를 잘랐습니다.",
        "나는 머리를 잘라야 합니다.",
        "그녀는 머리를 짧게 잘랐습니다.",
        "보통 어디에서 머리를 자르세요?"
      ]
    },
    {
      id: "a2-hair-04-06",
      type: "guided",
      level: "A2",
      part: 1,
      chapter: 1,
      unit: "3 · 04–06",
      title: "Shaving, Trimming & Perms",
      art: "剪",
      description: "머리를 밀고 다듬고 파마하는 미용실 행동 표현을 연습합니다.",
      summary: "have와 get을 활용한 미용실 표현을 완성 음원으로 듣고 따라 합니다.",
      durationLabel: "18:44",
      durationLong: "18 minutes 44 seconds",
      audio: "https://audio.talktag.co.kr/English/guided/A2/hair4-6%20A2.mp3",
      expressions: [
        "He had his hair shaved off.",
        "He decided to have his hair shaved off.",
        "She had her head shaved for the role.",
        "He shaved his head last summer.",
        "I had my hair trimmed last week.",
        "I just need to have my hair trimmed.",
        "She had her hair trimmed before the interview.",
        "I usually get my hair trimmed every month.",
        "She had her hair permed last month.",
        "Have your hair made curly.",
        "I'm thinking about having my hair permed.",
        "She had her hair permed at a salon.",
        "He doesn't want to have his hair permed."
      ],
      meanings: [
        "그는 머리를 완전히 밀었습니다.",
        "그는 머리를 완전히 밀기로 했습니다.",
        "그녀는 배역을 위해 머리를 밀었습니다.",
        "그는 지난여름에 머리를 밀었습니다.",
        "나는 지난주에 머리를 다듬었습니다.",
        "나는 머리만 조금 다듬으면 됩니다.",
        "그녀는 면접 전에 머리를 다듬었습니다.",
        "나는 보통 한 달에 한 번 머리를 다듬습니다.",
        "그녀는 지난달에 파마를 했습니다.",
        "머리를 곱슬거리게 해 보세요.",
        "나는 파마를 할까 생각 중입니다.",
        "그녀는 미용실에서 파마를 했습니다.",
        "그는 파마를 하고 싶어 하지 않습니다."
      ]
    },
    {
      id: "a2-hair-10-12",
      type: "guided",
      level: "A2",
      part: 1,
      chapter: 1,
      unit: "3 · 10–12",
      title: "Tying & Wearing Hair",
      art: "結",
      description: "머리를 묶고 포니테일로 하고 풀어 내리는 표현을 연습합니다.",
      summary: "일상에서 자주 쓰는 머리 모양 표현을 반복과 침묵 구간에 맞춰 따라 합니다.",
      durationLabel: "18:20",
      durationLong: "18 minutes 20 seconds",
      audio: "https://audio.talktag.co.kr/English/guided/A2/hair10-12%20A2.mp3",
      expressions: [
        "She tied her hair back with a rubber band.",
        "I usually tie my hair back at work.",
        "She tied her hair back before cooking.",
        "Can you tie your hair back?",
        "She was wearing her hair in a ponytail.",
        "I usually wear my hair in a ponytail.",
        "She wore her hair in a ponytail yesterday.",
        "I don't usually wear my hair in a ponytail.",
        "She let her hair down after work.",
        "She let her hair down before bed.",
        "I like to let my hair down at home.",
        "She let her hair down after tying it up all day."
      ],
      meanings: [
        "그녀는 고무줄로 머리를 뒤로 묶었습니다.",
        "나는 직장에서 보통 머리를 뒤로 묶습니다.",
        "그녀는 요리하기 전에 머리를 뒤로 묶었습니다.",
        "머리를 뒤로 묶어 줄래요?",
        "그녀는 머리를 포니테일로 하고 있었습니다.",
        "나는 보통 머리를 포니테일로 합니다.",
        "그녀는 어제 머리를 포니테일로 했습니다.",
        "나는 보통 머리를 포니테일로 하지 않습니다.",
        "그녀는 퇴근 후 묶었던 머리를 풀었습니다.",
        "그녀는 잠자리에 들기 전에 머리를 풀었습니다.",
        "나는 집에서 머리를 풀어 두는 것을 좋아합니다.",
        "그녀는 하루 종일 묶어 두었던 머리를 풀었습니다."
      ]
    },
    {
      id: "b1-head-brain",
      type: "guided",
      level: "B1",
      part: 1,
      chapter: 1,
      unit: 2,
      title: "Head & Brain",
      art: "頭",
      description: "머리의 움직임과 생각에 관한 동작·관용 표현을 반복 훈련합니다.",
      summary: "구체적인 동작부터 머리를 쓰는 관용 표현까지 듣고 자연스럽게 따라 합니다.",
      durationLabel: "16:39",
      durationLong: "16 minutes 39 seconds",
      audio: "https://audio.talktag.co.kr/English/guided/B1/head2%20B1.mp3",
      expressions: [
        "He bowed his head and said thank you.",
        "I scratched my head because I didn’t understand.",
        "She patted the child on the head.",
        "She stroked her daughter’s hair.",
        "He hit his head on the door.",
        "I hurt my head yesterday.",
        "He got hurt on the head while playing soccer.",
        "He has a head injury.",
        "Don’t bother your head about it.",
        "Don’t worry about it.",
        "You need to use your brain.",
        "Let’s put our brains to work.",
        "I racked my brains for an answer."
      ],
      meanings: [
        "그는 고개를 숙이며 감사하다고 말했습니다.",
        "나는 이해가 되지 않아 머리를 긁적였습니다.",
        "그녀는 아이의 머리를 토닥였습니다.",
        "그녀는 딸의 머리카락을 쓰다듬었습니다.",
        "그는 문에 머리를 부딪쳤습니다.",
        "나는 어제 머리를 다쳤습니다.",
        "그는 축구를 하다가 머리를 다쳤습니다.",
        "그는 머리를 다친 상태입니다.",
        "그 일로 너무 골치 아파하지 마세요.",
        "그 일은 걱정하지 마세요.",
        "머리를 좀 써야 합니다.",
        "함께 머리를 써 봅시다.",
        "나는 답을 찾으려고 머리를 쥐어짰습니다."
      ]
    },
    {
      id: "b1-hair-13-15",
      type: "guided",
      level: "B1",
      part: 1,
      chapter: 1,
      unit: "3 · 13–15",
      title: "Parting & Messing Up Hair",
      art: "分",
      description: "가르마를 타고 머리가 흐트러지는 표현과 관련 관용 표현을 익힙니다.",
      summary: "일상적인 머리 상태 표현에서 감정을 나타내는 관용 표현까지 확장합니다.",
      durationLabel: "16:24",
      durationLong: "16 minutes 24 seconds",
      audio: "https://audio.talktag.co.kr/English/guided/B1/hair13-15%20B1.mp3",
      expressions: [
        "He usually parts his hair to the left.",
        "I part my hair in the middle.",
        "She parts her hair on the right.",
        "He changed the way he parts his hair.",
        "The wind messed up my hair.",
        "Don't mess up my hair!",
        "The rain messed up my hair.",
        "My hair gets messed up easily.",
        "I've been tearing my hair out over this problem.",
        "I'm tearing my hair out trying to fix it.",
        "She was tearing her hair out over the mistake.",
        "This problem is making me tear my hair out."
      ],
      meanings: [
        "그는 보통 왼쪽으로 가르마를 탑니다.",
        "나는 가운데로 가르마를 탑니다.",
        "그녀는 오른쪽으로 가르마를 탑니다.",
        "그는 가르마 타는 방향을 바꿨습니다.",
        "바람 때문에 머리가 흐트러졌습니다.",
        "내 머리 흐트러뜨리지 마세요!",
        "비 때문에 머리가 흐트러졌습니다.",
        "내 머리는 쉽게 흐트러집니다.",
        "나는 이 문제 때문에 계속 머리를 쥐어뜯을 만큼 괴로워하고 있습니다.",
        "나는 이것을 고치려고 애쓰며 몹시 답답해하고 있습니다.",
        "그녀는 그 실수 때문에 무척 괴로워하고 있었습니다.",
        "이 문제 때문에 정말 미칠 것 같습니다."
      ]
    },
    {
      id: "b1-hair-16-17",
      type: "guided",
      level: "B1",
      part: 1,
      chapter: 1,
      unit: "3 · 16–17",
      title: "Hair Loss & Transplants",
      art: "育",
      description: "탈모의 변화와 모발이식을 이야기하는 표현을 연습합니다.",
      summary: "현재완료진행형과 선택·고민을 나타내는 표현을 반복 훈련합니다.",
      durationLabel: "11:33",
      durationLong: "11 minutes 33 seconds",
      audio: "https://audio.talktag.co.kr/English/guided/B1/hair16-17%20B1.mp3",
      expressions: [
        "I've been losing my hair lately.",
        "My dad started losing his hair in his thirties.",
        "I'm worried that I'm losing my hair.",
        "He has been losing his hair for years.",
        "He decided to get a hair transplant.",
        "He's considering getting a hair transplant.",
        "My uncle got a hair transplant.",
        "How much does it cost to get a hair transplant?"
      ],
      meanings: [
        "나는 요즘 머리카락이 계속 빠지고 있습니다.",
        "아버지는 삼십 대부터 머리카락이 빠지기 시작했습니다.",
        "나는 머리카락이 빠지는 것 같아 걱정입니다.",
        "그는 몇 년째 머리카락이 계속 빠지고 있습니다.",
        "그는 모발이식을 받기로 했습니다.",
        "그는 모발이식을 받을까 고민 중입니다.",
        "삼촌은 모발이식을 받았습니다.",
        "모발이식을 받는 데 비용이 얼마나 드나요?"
      ]
    }
  ];
})();
