window.TalkTagAudioLessons = [
  {
    "id": "guided-a1-01",
    "type": "guided",
    "level": "A1",
    "part": 1,
    "chapter": 1,
    "unit": 1,
    "title": "Put It Away",
    "art": "01",
    "description": "음식을 보관하고 주방을 정리할 때 쓰는 표현",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "9:22",
    "durationLong": "9:22",
    "audio": "https://audio.talktag.co.kr/English/guided/20261009-qc12/a1-01/training-10.mp3",
    "expressions": [
      "Put the milk in the fridge.",
      "Keep the ice cream in the freezer.",
      "Take the chicken out of the freezer.",
      "Wash the apples before you eat them.",
      "Put the leftovers in a container.",
      "Close the fridge door.",
      "Throw the empty box away.",
      "Let's clean up the kitchen."
    ],
    "meanings": [
      "우유를 냉장고에 넣으세요.",
      "아이스크림은 냉동실에 보관하세요.",
      "냉동실에서 닭고기를 꺼내세요.",
      "사과는 먹기 전에 씻으세요.",
      "남은 음식은 용기에 담으세요.",
      "냉장고 문을 닫으세요.",
      "빈 상자는 버리세요.",
      "주방을 함께 정리해요."
    ],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 561.8950113378685
    }
  },
  {
    "id": "guided-a1-02",
    "type": "guided",
    "level": "A1",
    "part": 2,
    "chapter": 1,
    "unit": 2,
    "title": "Make a Simple Snack",
    "art": "02",
    "description": "간단한 간식을 준비할 때 쓰는 표현",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "8:29",
    "durationLong": "8:29",
    "audio": "https://audio.talktag.co.kr/English/guided/20261009-qc12/a1-02/training-10.mp3",
    "expressions": [
      "Peel the apple first.",
      "Cut it into small pieces.",
      "Slice the cucumber really thin.",
      "Put everything in a bowl.",
      "Add a little salt.",
      "Pour in some dressing.",
      "Mix it all together.",
      "Now it's ready to eat."
    ],
    "meanings": [
      "먼저 사과 껍질을 벗기세요.",
      "작은 조각으로 자르세요.",
      "오이를 아주 얇게 썰어 주세요.",
      "모두 그릇에 담으세요.",
      "소금을 조금 넣으세요.",
      "드레싱을 조금 부으세요.",
      "모두 잘 섞으세요.",
      "이제 먹을 준비가 됐어요."
    ],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 508.86643990929707
    }
  },
  {
    "id": "guided-a2-01",
    "type": "guided",
    "level": "A2",
    "part": 1,
    "chapter": 1,
    "unit": 1,
    "title": "Making Breakfast",
    "art": "01",
    "description": "아침을 만들며 순서대로 말하는 표현",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "12:05",
    "durationLong": "12:05",
    "audio": "https://audio.talktag.co.kr/English/guided/20261009-qc12/a2-01/training-10.mp3",
    "expressions": [
      "I'm making breakfast before work.",
      "Can you boil some water for me?",
      "I'll crack two eggs into a bowl.",
      "Whisk them until they're well mixed.",
      "Heat the pan over medium heat.",
      "Pour the eggs into the pan.",
      "Toast two slices of bread.",
      "Spread some butter on the toast.",
      "I'll make coffee while the eggs cook.",
      "Breakfast will be ready in five minutes."
    ],
    "meanings": [
      "출근하기 전에 아침을 만들고 있어요.",
      "물 좀 끓여 줄 수 있어요?",
      "달걀 두 개를 깨서 그릇에 넣을게요.",
      "잘 섞일 때까지 거품기로 저으세요.",
      "팬을 중불로 달구세요.",
      "달걀물을 팬에 부으세요.",
      "빵 두 장을 구워 주세요.",
      "토스트에 버터를 조금 바르세요.",
      "달걀이 익는 동안 커피를 만들게요.",
      "5분이면 아침이 준비될 거예요."
    ],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 724.6371882086167
    }
  },
  {
    "id": "guided-a2-02",
    "type": "guided",
    "level": "A2",
    "part": 2,
    "chapter": 1,
    "unit": 2,
    "title": "Getting Dinner Ready",
    "art": "02",
    "description": "채소를 손질하고 식탁을 차릴 때 쓰는 표현",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 10회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "13:49",
    "durationLong": "13:49",
    "audio": "https://audio.talktag.co.kr/English/guided/20261009-qc12/a2-02/training-10.mp3",
    "expressions": [
      "I'm getting dinner ready now.",
      "Please rinse the vegetables under cold water.",
      "Chop the carrots into small pieces.",
      "Slice the mushrooms a little thinner.",
      "Heat some oil in a large pan.",
      "Add the vegetables and stir them around.",
      "Turn the heat down if they start cooking too fast.",
      "Can you set the table while I finish cooking?",
      "I'll serve the food in a minute.",
      "Let's save the leftovers for tomorrow."
    ],
    "meanings": [
      "지금 저녁을 준비하고 있어요.",
      "채소를 찬물에 헹궈 주세요.",
      "당근을 작게 썰어 주세요.",
      "버섯을 조금 더 얇게 썰어 주세요.",
      "큰 팬에 기름을 조금 두르고 달구세요.",
      "채소를 넣고 저어 가며 볶으세요.",
      "너무 빨리 익기 시작하면 불을 낮추세요.",
      "제가 요리를 마무리하는 동안 식탁을 차려 줄 수 있어요?",
      "곧 음식을 내놓을게요.",
      "남은 음식은 내일 먹을 수 있게 보관해요."
    ],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 10,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 827.9578231292517
    }
  },
  {
    "id": "guided-b1-01",
    "type": "guided",
    "level": "B1",
    "part": 1,
    "chapter": 1,
    "unit": 1,
    "title": "Dinner from What We Have",
    "art": "01",
    "description": "집에 있는 재료로 한 끼를 만들 때 쓰는 표현",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 15회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "26:35",
    "durationLong": "26:35",
    "audio": "https://audio.talktag.co.kr/English/guided/20261009-qc15/b1-01/training-15.mp3",
    "expressions": [
      "We don't have much food left, so let's use what we have.",
      "I found some vegetables that need to be used up today.",
      "Let's chop them up and cook them with some rice.",
      "We can add an egg if we want a little more protein.",
      "I'll heat the pan while you cut the vegetables.",
      "Don't turn the heat up too high, or the garlic will burn.",
      "If the rice is too dry, add a little water and stir it in.",
      "Let's taste it before we add any more salt.",
      "This actually turned out better than I expected.",
      "Pack the rest up so we can have it for lunch tomorrow."
    ],
    "meanings": [
      "남은 재료가 별로 없으니 있는 걸로 만들어 봐요.",
      "오늘 안에 다 써야 하는 채소가 좀 있네요.",
      "잘게 썰어서 밥과 함께 요리해요.",
      "단백질을 조금 더 보충하고 싶으면 달걀을 넣어도 돼요.",
      "채소를 자르는 동안 제가 팬을 달굴게요.",
      "불을 너무 세게 하면 마늘이 타니 조심하세요.",
      "밥이 너무 뻑뻑하면 물을 조금 넣고 섞으세요.",
      "소금을 더 넣기 전에 맛부터 봐요.",
      "생각했던 것보다 잘됐네요.",
      "나머지는 내일 점심으로 먹을 수 있게 담아 두세요."
    ],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 15,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 1594.1251700680273
    }
  },
  {
    "id": "guided-b1-02",
    "type": "guided",
    "level": "B1",
    "part": 2,
    "chapter": 1,
    "unit": 2,
    "title": "Around the Dinner Table",
    "art": "02",
    "description": "음식을 권하고 식사하며 대화할 때 쓰는 표현",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 15회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "21:29",
    "durationLong": "21:29",
    "audio": "https://audio.talktag.co.kr/English/guided/20261009-qc15/b1-02/training-15.mp3",
    "expressions": [
      "Go ahead and help yourself.",
      "Can you pass me the rice, please?",
      "Try the soup before it gets cold.",
      "This is good, but it could use a little more salt.",
      "I'll just have a small piece.",
      "Do you want some more, or are you full?",
      "I ate too fast because I was really hungry.",
      "Save some room for dessert.",
      "We can clear the table after everyone finishes.",
      "I'll put the leftovers away before we go to bed."
    ],
    "meanings": [
      "편하게 드세요.",
      "밥 좀 건네주시겠어요?",
      "국이 식기 전에 드셔 보세요.",
      "맛있는데 소금을 조금 더 넣으면 좋겠어요.",
      "저는 작은 조각 하나만 먹을게요.",
      "더 드실래요, 아니면 배부르세요?",
      "너무 배가 고파서 급하게 먹었어요.",
      "디저트 먹을 배는 좀 남겨 두세요.",
      "모두 식사를 마치면 식탁을 치우면 돼요.",
      "자기 전에 남은 음식을 정리해 둘게요."
    ],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 15,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 1288.2948979591836
    }
  },
  {
    "id": "guided-b2-01",
    "type": "guided",
    "level": "B2",
    "part": 1,
    "chapter": 1,
    "unit": 1,
    "title": "Cooking When You're in a Hurry",
    "art": "01",
    "description": "바쁜 날 요리 계획과 선택을 설명하는 표현",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 15회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "31:30",
    "durationLong": "31:30",
    "audio": "https://audio.talktag.co.kr/English/guided/20261009-qc15/b2-01/training-15.mp3",
    "expressions": [
      "I got home late, so I need to make something quick.",
      "Instead of cooking from scratch, I'm using a few things I already prepared.",
      "I'll heat the soup while the rice is warming up.",
      "The vegetables are already chopped, which saves a lot of time.",
      "If the sauce gets too thick, just add a splash of water.",
      "I'm keeping the heat fairly low so nothing sticks to the pan.",
      "We don't need anything fancy tonight; we just need something decent to eat.",
      "I'd rather make a simple meal than order food again.",
      "Once everything is hot, we can sit down and relax.",
      "On busy days, having a few basics ready makes a huge difference."
    ],
    "meanings": [
      "늦게 집에 와서 빨리 만들 수 있는 걸 해야겠어요.",
      "처음부터 전부 요리하는 대신 미리 준비해 둔 재료 몇 가지를 쓰고 있어요.",
      "밥을 데우는 동안 국을 데울게요.",
      "채소는 이미 썰어 놓아서 시간을 많이 절약할 수 있어요.",
      "소스가 너무 걸쭉해지면 물을 조금만 넣으세요.",
      "팬에 눌어붙지 않도록 불을 약하게 해 두었어요.",
      "오늘 저녁은 거창할 필요 없어요. 그냥 적당히 먹을 만한 게 있으면 돼요.",
      "또 음식을 주문하느니 간단하게라도 만들어 먹겠어요.",
      "음식이 모두 따뜻해지면 앉아서 편히 쉬어도 돼요.",
      "바쁜 날에는 기본 재료 몇 가지를 준비해 두는 것만으로도 정말 큰 차이가 나요."
    ],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 15,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 1888.9806122448979
    }
  },
  {
    "id": "guided-b2-02",
    "type": "guided",
    "level": "B2",
    "part": 2,
    "chapter": 1,
    "unit": 2,
    "title": "Having Friends Over",
    "art": "02",
    "description": "손님을 초대하고 식사 취향을 배려하는 표현",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 15회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "31:08",
    "durationLong": "31:08",
    "audio": "https://audio.talktag.co.kr/English/guided/20261009-qc15/b2-02/training-15.mp3",
    "expressions": [
      "A few friends are coming over, so I'm keeping the menu simple.",
      "I'm making one main dish and a couple of easy sides.",
      "One of my friends doesn't eat meat, so I'm making a separate option.",
      "I've already chopped most of the vegetables to save time later.",
      "Can you taste the sauce and tell me if it needs anything?",
      "I don't want the food to be too spicy for everyone.",
      "We can keep the dishes warm until the last person arrives.",
      "Once everyone's here, I'll put everything in the middle of the table.",
      "I like meals where people can serve themselves and try a little of everything.",
      "The food matters, but the point is really to spend time together."
    ],
    "meanings": [
      "친구 몇 명이 집에 올 예정이라 메뉴는 간단하게 준비하고 있어요.",
      "메인 요리 하나와 간단한 곁들임 요리 두어 가지를 만들고 있어요.",
      "친구 한 명이 고기를 먹지 않아서 별도 메뉴를 준비하고 있어요.",
      "나중에 시간을 아끼려고 채소는 대부분 미리 썰어 뒀어요.",
      "소스 맛을 보고 더 넣을 게 있는지 말해 줄래요?",
      "모두가 먹기에 음식이 너무 맵지는 않았으면 좋겠어요.",
      "마지막 사람이 올 때까지 음식은 따뜻하게 유지하면 돼요.",
      "다 모이면 음식을 식탁 가운데에 놓을게요.",
      "각자 덜어 먹으면서 이것저것 조금씩 맛볼 수 있는 식사가 좋아요.",
      "음식도 중요하지만, 결국 함께 시간을 보내는 게 목적이죠."
    ],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 15,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 1867.0374149659865
    }
  },
  {
    "id": "guided-c1-01",
    "type": "guided",
    "level": "C1",
    "part": 1,
    "chapter": 1,
    "unit": 1,
    "title": "Why I Cook at Home",
    "art": "01",
    "description": "집에서 요리하는 이유와 습관을 이야기하는 표현",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 15회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "42:54",
    "durationLong": "42:54",
    "audio": "https://audio.talktag.co.kr/English/guided/20261009-qc15/c1-01/training-15.mp3",
    "expressions": [
      "I don't cook at home because I think every meal has to be healthy or impressive.",
      "I mostly do it because I like knowing what goes into my food.",
      "When I make something myself, I can adjust the salt, oil, and spice as I go.",
      "It also makes me more aware of how much food I waste.",
      "Some nights I cook a proper meal, and other nights I just throw together whatever is left in the fridge.",
      "That flexibility is probably what keeps cooking from feeling like a chore.",
      "I've also gotten better at using ingredients before they go bad.",
      "Over time, I've learned that being a decent home cook is less about fancy recipes and more about knowing a few reliable techniques.",
      "For me, cooking is practical first, but there's something satisfying about making an ordinary meal well.",
      "That's usually enough to make me want to do it again the next day."
    ],
    "meanings": [
      "매 끼니가 건강하거나 근사해야 한다고 생각해서 집에서 요리하는 건 아니에요.",
      "무엇보다 제가 먹는 음식에 어떤 재료가 들어가는지 알고 싶어서예요.",
      "직접 만들면 요리하면서 소금, 기름, 매운맛을 조절할 수 있어요.",
      "요리를 하다 보면 제가 음식을 얼마나 낭비하는지도 더 의식하게 돼요.",
      "어떤 날은 제대로 된 식사를 만들고, 어떤 날은 냉장고에 남은 재료로 대충 한 끼를 만들어요.",
      "그런 융통성 덕분에 요리가 귀찮은 집안일처럼 느껴지지 않는 것 같아요.",
      "재료가 상하기 전에 활용하는 데도 더 능숙해졌어요.",
      "시간이 지나면서 집에서 요리를 제법 잘한다는 건 화려한 조리법보다 믿고 쓸 수 있는 몇 가지 조리 기술을 아는 데 달려 있다는 걸 배웠어요.",
      "제게 요리는 우선 실용적인 일이지만, 평범한 한 끼를 잘 만들어 내는 데서도 뿌듯함을 느껴요.",
      "그런 뿌듯함 덕분에 보통 다음 날도 요리하고 싶어져요."
    ],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 15,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 2573.3244897959185
    }
  },
  {
    "id": "guided-c1-02",
    "type": "guided",
    "level": "C1",
    "part": 2,
    "chapter": 1,
    "unit": 2,
    "title": "What Makes a Meal Feel Special",
    "art": "02",
    "description": "음식에 담긴 기억과 함께하는 시간을 이야기하는 표현",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 15회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "43:27",
    "durationLong": "43:27",
    "audio": "https://audio.talktag.co.kr/English/guided/20261009-qc15/c1-02/training-15.mp3",
    "expressions": [
      "A special meal doesn't always have to be expensive or carefully planned.",
      "Sometimes it's just familiar food served at the right moment.",
      "I've had simple meals that I remember more clearly than dinners at expensive restaurants.",
      "The difference was usually the people I was with and the mood around the table.",
      "Good food helps, of course, but it doesn't have to be complicated.",
      "A dish can be meaningful because someone took the time to make it for you.",
      "It can also remind you of a place, a person, or a particular period of your life.",
      "That's why certain smells or flavors can bring back memories almost instantly.",
      "For me, the best meals are the ones that make people slow down and stay at the table a little longer.",
      "The food gives everyone a reason to gather, but the conversation is what makes the meal memorable."
    ],
    "meanings": [
      "특별한 식사라고 해서 꼭 비싸거나 꼼꼼히 계획한 것이어야 하는 건 아니에요.",
      "때로는 알맞은 순간에 차려 낸 익숙한 음식이면 돼요.",
      "비싼 식당에서 먹은 저녁보다 더 선명하게 기억에 남는 소박한 식사도 있었어요.",
      "대개 그 차이를 만든 건 함께한 사람들과 식탁의 분위기였어요.",
      "물론 맛있는 음식도 도움이 되지만, 복잡한 요리일 필요는 없어요.",
      "누군가 시간을 들여 나를 위해 만들어 줬다는 이유만으로도 음식은 의미가 생길 수 있어요.",
      "어떤 장소나 사람, 또는 인생의 특정 시절을 떠올리게 할 수도 있어요.",
      "그래서 어떤 냄새나 맛은 거의 순식간에 추억을 불러오기도 해요.",
      "제게 가장 좋은 식사는 사람들이 서두르지 않고 식탁에 조금 더 오래 머물게 하는 식사예요.",
      "음식은 함께 모일 이유를 만들어 주지만, 그 식사를 기억에 남게 하는 건 대화예요."
    ],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 15,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 2606.2551020408164
    }
  },
  {
    "id": "guided-c2-01",
    "type": "guided",
    "level": "C2",
    "part": 1,
    "chapter": 1,
    "unit": 1,
    "title": "Convenience and Cooking Skills",
    "art": "01",
    "description": "요리의 편리함과 기본 기술의 균형을 이야기하는 표현",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 15회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "49:07",
    "durationLong": "49:07",
    "audio": "https://audio.talktag.co.kr/English/guided/20261009-qc15/c2-01/training-15.mp3",
    "expressions": [
      "Convenience in the kitchen is usually treated as a simple good, and most of the time it is.",
      "Pre-cut vegetables, delivery apps, and prepared meals can save time when life is busy.",
      "The trade-off is that convenience can gradually remove the need to practice basic skills.",
      "If you rarely chop, season, or cook from scratch, those actions can start to feel more difficult than they really are.",
      "That doesn't mean everyone needs to reject convenience or turn cooking into a hobby.",
      "It just means there is value in keeping a few basic skills alive.",
      "Knowing how to make a simple meal gives you options when plans change, money is tight, or you simply don't want to order out.",
      "The skill is modest, but the independence it creates is real.",
      "I think the best balance is to use convenience deliberately rather than automatically.",
      "Tools should make life easier without quietly making us less capable."
    ],
    "meanings": [
      "주방에서의 편리함은 대개 그저 좋은 것으로 여겨지고, 실제로 대부분은 그래요.",
      "미리 손질한 채소, 배달 앱, 조리된 음식은 바쁜 일상에서 시간을 아껴 줄 수 있어요.",
      "그 대신 편리함 때문에 기본 기술을 연습할 필요가 조금씩 사라질 수 있어요.",
      "직접 썰거나 간을 하거나 처음부터 요리하는 일이 드물면, 그런 동작들이 실제보다 더 어렵게 느껴지기 시작할 수 있어요.",
      "그렇다고 모두가 편리함을 거부하거나 요리를 취미로 삼아야 한다는 뜻은 아니에요.",
      "몇 가지 기본 기술을 잃지 않고 유지하는 데 가치가 있다는 뜻일 뿐이에요.",
      "간단한 한 끼를 만들 줄 알면 계획이 바뀌거나 돈이 빠듯하거나 그냥 음식을 주문하고 싶지 않을 때 선택지가 생겨요.",
      "대단한 기술은 아니지만, 그 기술이 만들어 주는 자립성은 분명해요.",
      "제 생각에 가장 좋은 균형은 편리함을 무심코 이용하기보다 의식적으로 선택해 활용하는 거예요.",
      "도구는 우리도 모르는 사이에 우리의 능력을 약화시키지 않으면서 삶을 더 편하게 해 줘야 해요."
    ],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 15,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 2946.3537414965986
    }
  },
  {
    "id": "guided-c2-02",
    "type": "guided",
    "level": "C2",
    "part": 2,
    "chapter": 1,
    "unit": 2,
    "title": "Why People Gather Around Food",
    "art": "02",
    "description": "함께 먹는 음식이 관계에 미치는 영향을 이야기하는 표현",
    "summary": "원어민의 음성을 듣고 한 문장씩 따라하세요. 각 문장을 15회 반복한 뒤 다음 문장으로 이어집니다.",
    "durationLabel": "50:44",
    "durationLong": "50:44",
    "audio": "https://audio.talktag.co.kr/English/guided/20261009-qc15/c2-02/training-15.mp3",
    "expressions": [
      "Food does more than solve hunger; it gives people a reason to gather without needing a formal agenda.",
      "A shared meal creates a natural structure for conversation because everyone is doing something together.",
      "That matters especially when people don't know one another well.",
      "Eating gives the group a common focus, which can make silence feel less awkward and conversation feel less forced.",
      "The meal itself may be simple, but the social effect can be surprisingly strong.",
      "People pass dishes, react to flavors, tell stories, and gradually become more comfortable with one another.",
      "In that sense, food often works as a kind of social bridge.",
      "It doesn't guarantee connection, and a good meal can't fix every relationship.",
      "But it can create the conditions in which people are more willing to stay, listen, and talk.",
      "Sometimes the most important thing on the table isn't the food at all; it's the time people have decided to share."
    ],
    "meanings": [
      "음식은 배고픔만 달래 주는 게 아니에요. 정해진 안건 없이도 사람들이 모일 이유를 만들어 줘요.",
      "함께 식사하면 모두가 같은 활동을 하고 있어서 대화가 자연스럽게 이어질 틀이 생겨요.",
      "서로를 잘 모르는 사람들 사이에서는 그 점이 특히 중요해요.",
      "먹는 일은 모두가 함께 집중할 대상을 만들어 주기 때문에 침묵이 덜 어색하고 대화도 덜 억지스럽게 느껴질 수 있어요.",
      "식사 자체는 소박할 수 있어도, 사람들을 이어 주는 효과는 놀랄 만큼 클 수 있어요.",
      "사람들은 음식을 건네고 맛에 대한 감상을 나누며 이야기하다가 점차 서로 편하게 느끼게 돼요.",
      "그런 의미에서 음식은 종종 사람들을 이어 주는 다리 역할을 해요.",
      "음식이 유대감을 보장하는 것은 아니고, 좋은 식사 한 번으로 모든 관계를 바로잡을 수도 없어요.",
      "하지만 사람들이 기꺼이 머물고, 듣고, 이야기할 수 있는 여건을 만들어 줄 수는 있어요.",
      "때로 식탁에서 가장 중요한 것은 음식이 아니라, 사람들이 함께 나누기로 한 시간이기도 해요."
    ],
    "training": {
      "kind": "sentence-repeat",
      "defaultReps": 15,
      "silenceMultiplier": 2.5,
      "startCueEnd": 0.5224489795918368,
      "endingCueStart": 3043.7244897959185
    }
  }
];
