window.TalkTagAudioLessons = (window.TalkTagAudioLessons || []).concat([
  {
    "id": "aea-a1-001",
    "level": "A1",
    "title": "A Quiet Morning",
    "expressions": [
      "Every morning, I get up at seven. I open the window and look outside. The street is quiet, and the air is cool.",
      "I make a cup of coffee and sit by the window. Sometimes, I listen to music. Sometimes, I just enjoy the quiet morning.",
      "At eight, I get ready for work. I put on my shoes, take my bag, and leave home.",
      "It is a simple morning, but I like it."
    ],
    "type": "plain",
    "unit": "001",
    "genre": "Daily Life",
    "art": "聴",
    "description": "조용한 아침",
    "summary": "이야기를 듣고, 기억한 내용을 노트에 정리한 뒤 내 말로 다시 이야기해 보세요.",
    "meanings": [
      "매일 아침 일곱 시에 일어납니다. 창문을 열고 밖을 내다봅니다. 거리는 조용하고 공기는 선선합니다.",
      "커피 한 잔을 만들어 창가에 앉습니다. 가끔 음악을 듣습니다. 가끔은 그저 조용한 아침을 즐깁니다.",
      "여덟 시에는 출근 준비를 합니다. 신발을 신고 가방을 챙겨 집을 나섭니다.",
      "평범한 아침이지만 저는 이런 시간이 좋습니다."
    ],
    "audio": "https://audio.talktag.co.kr/English/Audio%20Essays%20%26%20Articles/A1/A%20quiet%20morning%20A1%20Essay.mp3",
    "durationLabel": "00:28",
    "durationLong": "00:28",
    "titleKo": "조용한 아침",
    "referenceSummary": "The speaker enjoys a simple and quiet morning routine before going to work. A cup of coffee and a little quiet time make the morning pleasant."
  },
  {
    "id": "aea-a2-001",
    "level": "A2",
    "title": "The Little Bakery",
    "expressions": [
      "There is a small bakery near my house. I often stop there on my way home from work.",
      "The bakery is not big, but it always smells wonderful. They make fresh bread every afternoon. My favorite is the cheese bread, but sometimes I buy a chocolate cake for my family.",
      "The owner is an older woman named Mrs. Lee. She always smiles and asks me about my day.",
      "Yesterday, I was tired after work. I went into the bakery, bought some bread, and talked with Mrs. Lee for a few minutes.",
      "When I left, I felt much better.",
      "Sometimes, a small place can make a long day feel a little easier."
    ],
    "type": "plain",
    "unit": "001",
    "genre": "Mini Story",
    "art": "聴",
    "description": "작은 빵집",
    "summary": "이야기를 듣고, 기억한 내용을 노트에 정리한 뒤 내 말로 다시 이야기해 보세요.",
    "meanings": [
      "우리 집 근처에 작은 빵집이 있습니다. 퇴근길에 그곳에 자주 들릅니다.",
      "빵집은 크지 않지만 늘 좋은 냄새가 납니다. 매일 오후 갓 구운 빵을 만듭니다. 제가 가장 좋아하는 건 치즈빵이지만, 가끔 가족을 위해 초콜릿 케이크도 삽니다.",
      "주인은 이 씨라는 나이 지긋한 여성입니다. 늘 웃으며 오늘 하루는 어땠는지 물어봅니다.",
      "어제는 일을 마치고 피곤했습니다. 빵집에 들어가 빵을 사고 이 씨와 몇 분 동안 이야기를 나눴습니다.",
      "나올 때는 기분이 한결 나아졌습니다.",
      "때로는 작은 공간 하나가 길고 고단한 하루를 조금 더 편하게 느끼도록 해 줍니다."
    ],
    "audio": "https://audio.talktag.co.kr/English/Audio%20Essays%20%26%20Articles/A2/The%20Little%20Bakery%20A2%20Essay.mp3",
    "durationLabel": "00:43",
    "durationLong": "00:43",
    "titleKo": "작은 빵집",
    "referenceSummary": "The speaker often visits a small bakery near home. One tiring day, buying bread and talking with the friendly owner helps the speaker feel better."
  },
  {
    "id": "aea-b1-001",
    "level": "B1",
    "title": "Taking the Longer Way Home",
    "expressions": [
      "I usually take the fastest route home after work. I want to get home, eat dinner, and rest as soon as possible.",
      "But a few weeks ago, I started doing something different.",
      "Instead of taking the main road, I began walking through a small park near my neighborhood. It takes about fifteen minutes longer, but I don't mind.",
      "There are trees along the path, and I often see people walking their dogs or exercising. Sometimes I sit on a bench for a few minutes and watch people go by.",
      "At first, I thought I was wasting time. Then I noticed that I was arriving home in a better mood.",
      "The extra fifteen minutes give me time to leave the day behind.",
      "Now I understand that the fastest way home is not always the best way home."
    ],
    "type": "plain",
    "unit": "001",
    "genre": "Personal Essay",
    "art": "聴",
    "description": "조금 더 먼 길로 집에 가기",
    "summary": "이야기를 듣고, 기억한 내용을 노트에 정리한 뒤 내 말로 다시 이야기해 보세요.",
    "meanings": [
      "저는 퇴근할 때 보통 가장 빠른 길로 집에 갑니다. 가능한 한 빨리 집에 도착해 저녁을 먹고 쉬고 싶습니다.",
      "그런데 몇 주 전부터 조금 다른 방식으로 집에 가기 시작했습니다.",
      "큰길 대신 동네 근처의 작은 공원을 가로질러 걷기 시작했습니다. 15분쯤 더 걸리지만 저는 괜찮습니다.",
      "산책로를 따라 나무가 있고, 개를 산책시키거나 운동하는 사람들을 자주 봅니다. 가끔 벤치에 몇 분 동안 앉아 지나가는 사람들을 바라봅니다.",
      "처음에는 시간을 낭비한다고 생각했습니다. 그러다 집에 도착할 때 기분이 더 좋아진다는 걸 알아차렸습니다.",
      "그 15분 동안 하루의 일을 잠시 뒤로하고 마음을 정리할 수 있습니다.",
      "이제는 가장 빠른 귀갓길이 언제나 가장 좋은 길은 아니라는 걸 압니다."
    ],
    "audio": "https://audio.talktag.co.kr/English/Audio%20Essays%20%26%20Articles/B1/Taking%20the%20Longer%20Way%20Home%20B1%20Essay.mp3",
    "durationLabel": "00:52",
    "durationLong": "00:52",
    "titleKo": "조금 더 먼 길로 집에 가기",
    "referenceSummary": "The speaker starts taking a longer route home through a park. Although it takes more time, the walk helps the speaker relax and arrive home in a better mood."
  },
  {
    "id": "aea-b2-001",
    "level": "B2",
    "title": "Why We Need Places Where Nothing Is Expected of Us",
    "expressions": [
      "Most of the places we visit have a purpose.",
      "We go to the office to work, to the gym to exercise, and to a store to buy something. Even at home, there are often things waiting for us—laundry, dishes, messages, or unfinished work.",
      "That's why I think we need places where nothing is expected of us.",
      "For some people, that place is a quiet café. For others, it might be a park, a library, or even a bench beside a river.",
      "The important thing is not the location itself. What matters is that, for a short time, we don't have to accomplish anything.",
      "Modern life encourages us to use every minute efficiently. We listen to podcasts while walking, answer messages while eating, and check our phones whenever we have a free moment.",
      "None of these habits is necessarily bad. The problem begins when we forget how to simply be somewhere.",
      "A quiet twenty minutes may look unproductive from the outside. Yet those twenty minutes can give our minds space to slow down, notice things, and recover.",
      "Perhaps rest is not the opposite of doing something useful.",
      "Perhaps sometimes, rest is the useful thing."
    ],
    "type": "plain",
    "unit": "001",
    "genre": "Lifestyle Article",
    "art": "聴",
    "description": "아무것도 하지 않아도 되는 곳이 필요한 이유",
    "summary": "이야기를 듣고, 기억한 내용을 노트에 정리한 뒤 내 말로 다시 이야기해 보세요.",
    "meanings": [
      "우리가 찾아가는 대부분의 장소에는 목적이 있습니다.",
      "회사에는 일하러, 헬스장에는 운동하러, 가게에는 물건을 사러 갑니다. 집에서도 빨래와 설거지, 메시지, 끝내지 못한 일이 우리를 기다릴 때가 많습니다.",
      "그래서 저는 우리에게 아무것도 요구하지 않는 공간이 필요하다고 생각합니다.",
      "어떤 사람에게는 그곳이 조용한 카페입니다. 다른 사람에게는 공원이나 도서관, 강가의 벤치일 수도 있습니다.",
      "중요한 것은 장소 자체가 아닙니다. 잠시라도 무언가를 해내야 한다는 부담에서 벗어날 수 있다는 점이 중요합니다.",
      "현대의 삶은 매 순간을 효율적으로 쓰라고 우리를 재촉합니다. 우리는 걸으면서 팟캐스트를 듣고, 식사하며 메시지에 답하고, 잠깐 시간이 날 때마다 휴대전화를 확인합니다.",
      "이런 습관이 꼭 나쁜 것은 아닙니다. 그저 한곳에 가만히 머무는 법을 잊어버릴 때 문제가 시작됩니다.",
      "조용히 보내는 20분은 겉으로 보면 비생산적으로 보일 수 있습니다. 하지만 그 20분은 마음의 속도를 늦추고 주변을 살피며 회복할 여유를 줍니다.",
      "어쩌면 휴식은 유용한 일과 반대되는 것이 아닐지도 모릅니다.",
      "때로는 쉬는 것 자체가 유용한 일일 수 있습니다."
    ],
    "audio": "https://audio.talktag.co.kr/English/Audio%20Essays%20%26%20Articles/B2/Why%20We%20Need%20Places%20Where%20Nothing%20Is%20Expected%20of%20Us%20B2%20Essay.mp3",
    "durationLabel": "01:20",
    "durationLong": "01:20",
    "titleKo": "아무것도 하지 않아도 되는 곳이 필요한 이유",
    "referenceSummary": "Modern life constantly gives us things to do. The article argues that we need places where nothing is expected of us because quiet, apparently unproductive time can help our minds slow down and recover."
  },
  {
    "id": "aea-c1-001",
    "level": "C1",
    "title": "The Disappearing Art of Being Temporarily Unavailable",
    "expressions": [
      "There was a time when being unreachable was an ordinary part of daily life.",
      "Someone could leave the house in the morning, spend several hours away, and return without having received a single message. Unless there was an emergency, nobody found this particularly strange.",
      "Smartphones have quietly changed that expectation.",
      "Today, carrying a phone often means carrying an invisible obligation to remain available. A message arrives, we see it, and a small decision immediately follows: Should I answer now? Can it wait? Will the other person think I'm ignoring them?",
      "Individually, these decisions seem insignificant. Collectively, however, they create a subtle form of mental pressure.",
      "The issue is not simply that technology distracts us. Technology has also changed what other people can reasonably expect from us. Once instant communication becomes possible, delayed communication can begin to look intentional.",
      "This makes genuine disconnection surprisingly difficult.",
      "Turning off notifications helps, but it doesn't completely solve the problem because the expectation remains in our minds. We know that messages may be waiting.",
      "Perhaps what we need, then, is not another productivity technique but a renewed social agreement: people should be allowed to disappear for a while.",
      "A walk without a phone, an unanswered message during dinner, or an afternoon spent offline should not require an explanation.",
      "Being temporarily unavailable is not necessarily a rejection of other people.",
      "Sometimes it is simply a way of becoming fully available to the life directly in front of us."
    ],
    "type": "plain",
    "unit": "001",
    "genre": "Social Commentary",
    "art": "聴",
    "description": "잠시 연락이 닿지 않아도 되는 자유",
    "summary": "이야기를 듣고, 기억한 내용을 노트에 정리한 뒤 내 말로 다시 이야기해 보세요.",
    "meanings": [
      "연락이 되지 않는 시간이 일상의 자연스러운 일부였던 시절이 있었습니다.",
      "아침에 집을 나서 몇 시간 동안 밖에 있다가 메시지 하나 받지 않고 돌아올 수도 있었습니다. 긴급한 일이 아니라면 누구도 이를 특별히 이상하게 여기지 않았습니다.",
      "스마트폰은 그런 기대를 조용히 바꿔 놓았습니다.",
      "이제 휴대전화를 들고 다닌다는 것은 언제든 연락받을 수 있어야 한다는 보이지 않는 의무까지 지닌다는 뜻일 때가 많습니다. 메시지가 도착해 확인하는 순간 작은 결정을 내려야 합니다. 지금 답해야 할까? 나중에 답해도 될까? 상대가 내가 무시한다고 생각하지 않을까?",
      "이런 결정은 하나씩 보면 사소해 보입니다. 하지만 모이면 눈에 잘 띄지 않는 정신적 압박이 됩니다.",
      "문제는 단순히 기술이 우리의 집중을 방해한다는 데 있지 않습니다. 기술은 다른 사람들이 우리에게 당연히 기대할 수 있는 것까지 바꿨습니다. 즉시 소통할 수 있게 되면 답장이 늦는 것조차 일부러 그러는 것처럼 보이기 시작합니다.",
      "그래서 연락을 완전히 끊고 쉬는 일이 생각보다 어렵습니다.",
      "알림을 끄면 도움이 되지만, 마음속에 기대가 남아 있어 문제가 완전히 해결되지는 않습니다. 확인하지 않은 메시지가 기다리고 있을 수 있다는 걸 알고 있기 때문입니다.",
      "어쩌면 필요한 것은 또 다른 생산성 기법이 아니라, 누구나 잠시 연락이 닿지 않아도 된다는 새로운 사회적 합의입니다.",
      "휴대전화 없이 산책하거나, 저녁 식사 중 메시지에 답하지 않거나, 오후를 오프라인으로 보내는 일에 이유를 설명할 필요는 없어야 합니다.",
      "잠시 연락이 되지 않는다고 해서 다른 사람을 거부하는 것은 아닙니다.",
      "때로는 바로 눈앞의 삶에 온전히 집중하기 위한 방법일 뿐입니다."
    ],
    "audio": "https://audio.talktag.co.kr/English/Audio%20Essays%20%26%20Articles/C1/The%20Disappearing%20Art%20of%20Being%20Temporarily%20Unavailable%20C1%20Essay.mp3",
    "durationLabel": "01:56",
    "durationLong": "01:56",
    "titleKo": "잠시 연락이 닿지 않아도 되는 자유",
    "referenceSummary": "Smartphones have created an expectation that people should always be reachable. The essay argues that constant availability creates subtle mental pressure and that society should accept temporary disconnection as a normal and healthy part of life."
  },
  {
    "id": "aea-c2-001",
    "level": "C2",
    "title": "The Things We Stop Noticing",
    "expressions": [
      "One of the peculiar consequences of familiarity is that it gradually makes the visible world disappear.",
      "When we enter an unfamiliar neighborhood, almost everything demands our attention: the shape of the buildings, the rhythm of the traffic, fragments of conversation, the smell drifting from a restaurant whose name we cannot pronounce. We are alert because we do not yet know what matters.",
      "Return to the same place every day, however, and much of this richness begins to fade.",
      "The bakery on the corner becomes simply \"the bakery.\" The elderly man who waters the plants outside his shop becomes part of the scenery. Even the changing light on buildings we have passed a thousand times can cease to register.",
      "This fading of attention is not a defect. Without it, ordinary life would overwhelm us. The brain becomes efficient precisely by deciding what it no longer needs to examine closely.",
      "Yet efficiency carries a subtle cost.",
      "When familiarity tells us that we already know a place, a person, or even an idea, curiosity tends to withdraw. We stop looking because we assume there is nothing left to see.",
      "The same phenomenon occurs in relationships. A stranger's story can fascinate us because every detail is new. With someone we have known for twenty years, we may begin to believe that we already understand the entire person.",
      "Of course, we don't.",
      "People continue to change beneath the identities we assign to them, just as familiar streets continue to change beneath our routines.",
      "Perhaps attention, then, is not merely something the world captures from us. It is something we can deliberately return to the world.",
      "We can take a different street home. We can ask an old friend a question we have never asked. We can sit in a familiar room and notice what has been there all along.",
      "The remarkable does not always require discovery.",
      "Sometimes it requires rediscovery."
    ],
    "type": "plain",
    "unit": "001",
    "genre": "Reflective Essay",
    "art": "聴",
    "description": "우리가 더 이상 눈여겨보지 않는 것들",
    "summary": "이야기를 듣고, 기억한 내용을 노트에 정리한 뒤 내 말로 다시 이야기해 보세요.",
    "meanings": [
      "익숙함이 가져오는 묘한 결과 중 하나는 눈앞의 세상이 서서히 보이지 않게 된다는 것입니다.",
      "낯선 동네에서는 건물의 모양, 차들이 오가는 흐름, 스쳐 가는 대화, 이름을 발음하기 어려운 식당의 냄새까지 거의 모든 것이 우리의 관심을 끕니다. 아직 무엇이 중요한지 모르기 때문에 주변을 세심하게 살핍니다.",
      "하지만 같은 장소에 매일 가면 그 생생한 모습이 조금씩 희미해집니다.",
      "모퉁이의 빵집은 그저 “그 빵집”이 되고, 가게 앞 화분에 물을 주는 노인은 풍경의 일부가 됩니다. 수없이 지나친 건물 위로 달라지는 빛조차 더 이상 의식하지 않게 될 수 있습니다.",
      "이처럼 주의가 무뎌지는 것은 결함이 아닙니다. 그런 변화가 없다면 평범한 일상조차 감당하기 버거울 것입니다. 뇌는 더 이상 자세히 살필 필요가 없는 것을 판단함으로써 효율적으로 작동합니다.",
      "하지만 효율에는 눈에 잘 띄지 않는 대가가 따릅니다.",
      "장소나 사람, 생각까지 이미 잘 안다고 느끼면 호기심은 줄어들기 쉽습니다. 더 볼 것이 없다고 여기기 때문에 살펴보기를 멈춥니다.",
      "인간관계에서도 같은 현상이 일어납니다. 낯선 사람의 이야기는 모든 세부 내용이 새로워서 흥미롭게 들릴 수 있습니다. 반면 20년 동안 알고 지낸 사람은 이미 전부 이해한다고 믿기 시작할 수도 있습니다.",
      "물론 실제로는 그렇지 않습니다.",
      "익숙한 거리가 늘 같은 일상 속에서도 달라지듯, 사람도 우리가 붙인 이미지 너머에서 계속 변합니다.",
      "그렇다면 관심은 세상이 우리에게서 끌어내는 것만은 아닐지도 모릅니다. 우리가 의식적으로 다시 세상에 기울일 수도 있습니다.",
      "평소와 다른 길로 집에 갈 수 있습니다. 오래된 친구에게 한 번도 하지 않았던 질문을 할 수 있습니다. 익숙한 방에 앉아 늘 그곳에 있던 것을 새롭게 눈여겨볼 수도 있습니다.",
      "놀라운 것을 만나려면 언제나 새로운 발견이 필요한 것은 아닙니다.",
      "때로는 이미 알고 있던 것을 다시 발견해야 합니다."
    ],
    "audio": "https://audio.talktag.co.kr/English/Audio%20Essays%20%26%20Articles/C2/The%20Things%20We%20Stop%20Noticing%20C2%20Essay.mp3",
    "durationLabel": "02:23",
    "durationLong": "02:23",
    "titleKo": "우리가 더 이상 눈여겨보지 않는 것들",
    "referenceSummary": "Familiarity helps the brain operate efficiently, but it can also cause us to stop noticing familiar places, people, and experiences. The essay suggests that we can deliberately restore our attention and rediscover what has been around us all along."
  }
]);
